version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: railway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: peXsANTJCurVmgPNOvCIDTLAjaTdDvyz
    ports:
      - "5432:5432"

    app:
      build: .
      environment:
        - DATABASE_URL=${DATABASE_URL}
        - PGUSER=${PGUSER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      ports:
        - "8080:8080"
      depends_on:
        - db