[build]
builder = "NIXPACKS"
buildCommand = "./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -jar target/gestion-estudiante-0.0.1-SNAPSHOT.jar"
restartPolicyType = "ON_FAILURE"
cleanBuild = true